// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 James Luna

package dev.viewdock.android.ui

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The About screen shows these bundled texts verbatim, so they have to exist and say what
 * the GPL requires an interactive program to say. (The files are generated by
 * `scripts/generate_legal.py`; a host test checks they are up to date.)
 */
class LegalAssetsTest {
    // Unit tests run with the module directory (`android/app`) as the working directory.
    private fun asset(path: String) = File("src/main/assets/$path").readText()

    @Test
    fun theFullGplTextIsBundled() {
        val text = asset(LegalInfo.LICENSE_ASSET)
        assertTrue(text.contains("GNU GENERAL PUBLIC LICENSE"))
        assertTrue(text.contains("Version 3, 29 June 2007"))
    }

    @Test
    fun theNoticesCarryTheCopyrightTheNoWarrantyStatementAndTheSourceLink() {
        val text = asset(LegalInfo.NOTICES_ASSET)
        assertTrue(text.contains(LegalInfo.COPYRIGHT))
        assertTrue(text.contains("ABSOLUTELY NO WARRANTY"))
        assertTrue(text.contains(LegalInfo.SOURCE_URL))
    }

    @Test
    fun theNoticesReproduceTheLicensesOfTheLibrariesTheAppShips() {
        val text = asset(LegalInfo.NOTICES_ASSET)
        assertTrue(text.contains("Apache License"))
        // MIT / BSD require their copyright line to travel with the software.
        assertTrue(text.contains("Copyright (c) 2010-2020 Nathan Rajlich"))
        assertTrue(text.contains("Copyright (c) 2004-2025 QOS.ch"))
        assertTrue(text.contains("Copyright (c) 2011, The WebRTC project authors"))
    }

    @Test
    fun theCopyrightLineIsTheSameEverywhere() {
        assertEquals("Copyright (C) 2026 James Luna", LegalInfo.COPYRIGHT)
    }
}
